# Generated by Django 4.0.4 on 2022-08-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('1', '혼밥'), ('2', '혼술'), ('3', '혼카페'), ('4', '혼놀')], max_length=3),
        ),
    ]
