# Generated by Django 4.0.4 on 2022-08-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0002_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('1', '혼밥'), ('2', '혼술'), ('3', '혼카페'), ('4', '혼놀')], max_length=3),
        ),
    ]
