# Generated by Django 4.0.4 on 2022-08-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0003_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
